GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/6335ac56eb19b09bed6b9ec3

### expect "malformatted id" error
GET http://localhost:3003/api/blogs/6335ac56eb19b09bed6b9ec

### expect 404 not found error
GET http://localhost:3003/api/blogs/6335ac56eb19b09bed6b9eca